# DataSource Config
spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000ms
  elasticsearch:
    rest:
      connection-timeout: 2s # 连接超时时间
      read-timeout: 30s # 读取超时时间
      uris: [http://localhost:9200]

  aop:
    proxy-target-class: true
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  address: 0.0.0.0
  port: 8084
